version: '3'
services:
    digital-fuesim-manv:
        depends_on:
            - db
        image: digitalfuesimmanv/dfm
        # Use this to build the container for yourself:
        #build:
        #    context: .
        #    dockerfile: docker/Dockerfile
        restart: unless-stopped
        container_name: digital-fuesim-manv
        ports:
            - 80:80
        # uncomment port 443 if HTTPS is used
        #    - 443:443
        # all available ENVs are listed here with their default value set
        #environment:
        #    - DOMAIN=           # please set your desired domain name
        #    - SSL_ENABLE=false  # enabling this will enable https, needs DOMAIN set, disabling again will not delete content in the ssl volume
        #    - ENABLE_HSTS=false # WARNING enabling this once will make so you can't go back to http, only activate after you tested https works
        env_file:
            - .env
        volumes:
            - ssl:/ssl
    db:
        image: postgres:14
        container_name: dfm_postgres
        volumes:
            - dfm_db:/var/lib/postgresql/data
        # Use this to expose the database to your host machine
        # ports:
        #     - 127.0.0.1:${DFM_DB_PORT}:5432
        environment:
            - POSTGRES_USER=${DFM_DB_USER}
            - POSTGRES_PASSWORD=${DFM_DB_PASSWORD}
            - POSTGRES_DB=${DFM_DB_NAME}

volumes:
    # database is in this volume
    dfm_db:
    # needed to keep persistency with SSL
    ssl: